### ISSUE TITLE
Design of Material Theme Builder page is broken

### ISSUE THREAD

**Issue by AxelBriche** [material-foundation/material-theme-builder#129]
This page is broken:
https://m3.material.io/theme-builder

<img width="2345" alt="CleanShot 2023-03-02 at 19 35 18@2x" src="https://user-images.githubusercontent.com/1295251/222520692-674ef2e7-6646-4365-9a21-559195c09716.png">

<img width="2346" alt="CleanShot 2023-03-02 at 19 37 01@2x" src="https://user-images.githubusercontent.com/1295251/222521021-5ad3dee6-04a1-4a9d-a277-4e02153c40d6.png">

**Comment by SmallScreenDesign** [comment]
Still broken.

**Comment by JeanMeche** [comment]
There seems to be a problem in the JS code: `Identifier '_customElementsDefine' has already been declared `

**Comment by jwill** [comment]
There was a problem that caused icons to not render properly but it has since been resolved in the app that hosts Material Theme Builder.

Fixed/Unable to reproduce.

**Comment by Mamadzhanov** [comment]
@jwill ,
The problem is still exists. I was able to reproduce the same problem.
Browser: Chrome 115 (64 Bit)
Platform: Windows 11.

Uploading an image doesn't work.
