### ISSUE TITLE
Displaying and exporting wrong colours 

### ISSUE THREAD

**Issue by steamedham544** [material-foundation/material-theme-builder#73]
**Describe the bug**
- Entering key colours not displaying correctly and automatically changes.
- Exporting doesn't export whatever is displayed. It seems to download some default theme.

**To Reproduce**
I'm trying to generate the following theme: https://m3.material.io/styles/color/the-color-system/color-roles

Primary: #3a691e
Secondary: #55624c
Tertiary: #19686a
Neutral: #5d5f5a

**Expected behavior**
- Generate colours as seen here: https://m3.material.io/styles/color/the-color-system/color-roles
- Download the generated theme.

**Screenshots**
![Generated light theme](https://user-images.githubusercontent.com/99104240/174455432-7b422d3f-df33-455d-b121-8a80e790b657.PNG)

![Generated dark theme](https://user-images.githubusercontent.com/99104240/174455443-e045d958-dcc2-4933-b53a-5f3529239d6f.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 102.0.5005.115

**Smartphone (please complete the following information):**

**Additional context**
Every time I export for Android I get some sort of default theme being created no matter what I change:
[material-theme.zip](https://github.com/material-foundation/material-theme-builder/files/8934265/material-theme.zip)

**Comment by macxtor** [comment]
I agree, I'm having same problem

**Comment by Nohus** [comment]
Any update? This makes the tool useless since you can't actually export the theme you create in it.

**Comment by jwill** [comment]
I'm not able to reproduce this...do you happen to have multiple downloads blocked by default? Sometimes that will make downloads not act as expected.

**Comment by Nohus** [comment]
Here is what I'm doing:

- Go to the custom tab
- Select some primary/secondary colors
- Click Export / Jetpack Compose

The downloaded .zip file contains default colors, not the actual color scheme.

**Comment by jwill** [comment]
And to confirm, you don't have multiple downloads blocked? Does a red x show up in URL bar with Download blocked or when you try to export?

**Comment by ahmedre** [comment]
I am able to 100% reproduce this in Safari on macOS, for example (though on Google Chrome, it works properly).

**Comment by jwill** [comment]
Fixed in recent push.

**Comment by eygraber** [comment]
This is either still happening, or happening again. I'm seeing the same exact behavior as described above. I set a primary, secondary, and tertiary color, but the primary color is used for secondary and tertiary as well.

**Comment by eygraber** [comment]
Apologies, I misread. This is a similar, but different issue. I will open a new one.
